[package]
name = "silvioinstall"
version = "0.1.0"
edition = "2024"
authors = ["Silvio Ramalho Neto da Silva"]
license = "GPL-3.0-or-later"
description = "SilvioLinux Installer"
repository = "https://github.com/SilvioRamalhoNetodaSilva/silvioinstall/"
readme = "README.md"

[[bin]]
name = "silvioinstall"
path = "src/main.rs"

[dependencies]
fltk = "=1.5.22"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
incremental = false
